"""Added sale_price to models

Revision ID: 639438cb91d6
Revises: 8b580be780b2
Create Date: 2022-06-09 08:51:37.740081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '639438cb91d6'
down_revision = '8b580be780b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('sale_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'sale_price')
    # ### end Alembic commands ###
